package com.template.mlevytskiy;

import android.text.TextUtils;

import com.template.mlevytskiy.vo.MorePopular;

import org.apache.commons.lang.ArrayUtils;

/**
 * Created by Макс on 17.07.2014.
 */
public class MorePopularIrregularVerbs {

    public String[] get20() {
        return new String[] {
               "say", "make", "go", "take", "come", "see", "know", "get", "give", "find",
                "think", "tell", "become", "show", "leave", "feel", "put", "bring", "begin",
                "keep"
        };
    }

    public String[] get50() {
        return (String[]) ArrayUtils.addAll(new String[] {
            "hold", "write", "stand", "hear", "let", "mean", "set", "meet", "run", "pay", "sit",
             "speak", "lie", "lead", "read", "grow", "lose", "fall", "send", "build", "understand",
             "draw", "break", "spend", "cut", "rise", "drive", "buy", "wear", "choose", "can"
        }, get20()) ;
    }

    public String[] get100() {
        return new String[] {
        "arise", "be", "bear", "become", "begin", "bent", "bind", "bite", "bleed", "blow", "break",
        "breed", "bring", "build", "burn", "buy", "cast", "catch", "choose", "come", "cost", "cut",
        "dig", "do", "draw", "dream", "drink", "drive", "eat", "fall", "feed", "feel", "fight",
        "find", "flee", "fly", "forget", "get", "give", "go", "grow", "hang", "have", "hear", "hide",
        "hold", "keep", "know", "lead", "learn", "leave", "lend", "let", "light", "lose", "make",
        "mean", "meet", "put", "read", "ride", "rise", "run", "say", "see", "sell", "send", "set",
        "shake", "shine", "shoot", "shut", "sing", "sink", "sit", "sleep", "smell", "speak", "spend",
        "spoil", "spread", "spring", "stand", "steal", "strike", "strive", "swear", "swim", "take",
        "teach", "tear", "tell", "think", "throw", "understand", "wear", "weep", "win", "wind",
        "write", "can"
        };
    }

    public String[] getNormalPopularWords() {
        return new String[]{
                "abide",
                "arise",
                "awake",
                "backbite",
                "backslide",
                "be",
                "bear",
                "beat",
                "become",
                "befall",
                "beget",
                "begin",
                "begird",
                "behold",
                "bend",
                "bereave",
                "beseech",
                "beset",
                "bespeak",
                "bespit",
                "bestride",
                "bet",
                "betake",
                "bid",
                "bind",
                "bite",
                "bleed",
                "bless",
                "blow",
        "break",
        "bring",
                "broadcast",
        "browbeat",
                "build",
        "burn",
                "burst",
        "bust",
                "buy",
                "cast",
        "catch",
        "chide",
                "choose",
        "cleave",
                "cling",
        "come",
                "can",
                "cost",
        "countersink",
                "creep",
        "crow",
                "cut",
                "dare",
        "deal",
                "dig",
        "dive",
        "do",
            "draw",
                    "dream",
        "drink",
                "drive",
        "dwell",
        "eat",
        "fall",
                "feed",
        "feel",
                "fight",
        "find",
                "flee",
        "fling",
                "floodlight",
        "fly",
                "forbear",
        "forbid",
                "forecast",
        "foresee",
                "foretell",
        "forget",
                "forgive",
        "forsake",
                "forswear",
        "freeze",
        "gainsay",
                "get",
        "gild",
                "gird",
        "give",
                "go",
        "grave",
                "grind",
        "grow",
        "hamstring",
                "hang",
        "have",
                "hear",
        "heave",
                "hew",
        "hide",
                "hit",
        "hold",
                "hurt",
                "inlay",
        "input",
                "inset",
        "interweave",
        "keep",
                "ken",
        "kneel",
                "knit",
        "know",
        "lade",
                "lay",
        "lead",
                "lean",
        "leap",
                "learn",
        "leave",
                "lend",
        "let",
                "lie",
        "light",
                "lose",
                "make",
        "may",
                "mean",
        "meet",
                "miscast",
        "misdeal",
                "misgive",
        "mishear",
                "mishit",
        "mislay",
                "mislead",
        "misread",
                "misspell",
        "misspend",
                "mistake",
        "misunderstand",
                "mow",
                "outbid",
        "outdo",
                "outfight",
        "outgrow",
                "output",
        "outrun",
                "outsell",
        "outshine",
                "overbid",
        "overcome",
                "overdo",
        "overdraw",
                "overeat",
        "overfly",
                "overhang",
        "overhear",
                "overlay",
        "overpay",
                "override",
        "overrun",
                "oversee",
        "overshoot",
                "oversleep",
        "overtake",
                "overthrow",
                "partake",
        "pay",
                "plead",
        "prepay",
                "prove",
        "put",
        "quit",
        "read",
                "rebind",
        "rebuild",
                "recast",
        "redo",
                "rehear",
        "remake",
                "rend",
        "repay",
                "rerun",
        "resell",
                "reset",
        "resit",
                "retake",
        "retell",
                "rewrite",
        "rid",
                "ride",
        "ring",
                "rise",
        "rive",
                "run",
                "saw",
        "say",
                "see",
        "seek",
                "sell",
        "send",
                "set",
        "sew",
                "shake",
        "shave",
                "shear",
        "shed",
                "shine",
        "shoe",
                "shoot",
        "show",
                "shred",
        "shrink",
                "shrive",
        "shut",
                "sing",
        "sink",
                "sit",
        "slay",
                "sleep",
        "slide",
                "sling",
        "slink",
                "slit",
        "smell",
                "smite",
        "sow",
                "speak",
        "speed",
                "spell",
        "spend",
                "spill",
        "spin",
                "spit",
        "split",
                "spoil",
        "spotlight",
                "spread",
        "spring",
                "stand",
        "stave",
                "steal",
        "stick",
                "sting",
        "stink",
                "strew",
        "stride",
                "strike",
        "string",
                "strive",
        "sublet",
                "swear",
        "sweep",
                "swell",
        "swim",
                "swing",
                "take",
        "teach",
                "tear",
        "tell",
                "think",
        "thrive",
        "throw",
                "thrust",
        "tread",
        "unbend",
                "underbid",
        "undercut",
                "undergo",
        "underlie",
                "underpay",
        "undersell",
                "understand",
        "undertake",
                "underwrite",
        "undo",
                "unfreeze",
        "unsay",
                "unwind",
        "uphold",
                "upset",
                "wake",
        "waylay",
                "wear",
        "weave",
                "wed",
        "weep",
                "wet",
        "win",
                "wind",
        "withdraw",
                "withhold",
        "withstand",
                "work",
        "wring",
                "write",

        };
    }

    public void init(MorePopular morePopular) {
        String[] morePopular100 = get100();
        String form1 = morePopular.getForm1SimpleStr();

        for (String word100 : morePopular100) {
            if (TextUtils.equals(form1, word100)) {
                morePopular.setMorePopular100(true);
                String[] morePopular50 = get50();
                for (String word50 : morePopular50) {
                    if (TextUtils.equals(form1, word50)) {
                        morePopular.setMorePopular50(true);
                        String[] morePopular20 = get20();
                        for (String word20 : morePopular20) {
                            if (TextUtils.equals(form1, word20)) {
                                morePopular.setMorePopular20(true);
                            }
                        }
                    }
                }
            }
        }

        if (!morePopular.isMorePopular100()) {
            //try init less popular field
            morePopular.setLessPopular(true);
            for (String normalPopularWord : getNormalPopularWords()) {
                if (TextUtils.equals(form1, normalPopularWord)) {
                    morePopular.setLessPopular(false);
                }
            }
        }
    }
}
